[project]
name = "redstone-computer-utilities"
description = "Python Library for Redstone Computer Utilities."
authors = [{ name = "NKID00", email = "nkid0000@gmail.com" }]
readme = "docs/PyPI.md"
license = "MPL-2.0"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dynamic = ["version"]

[tool.maturin]
features = ["pyo3/extension-module", "pyo3/generate-import-lib"]
python-source = "python"
module-name = "redstone_computer_utilities.rcu_shim"

[build-system]
requires = ["maturin>=1.9,<2.0"]
build-backend = "maturin"
